# Generated by Django 4.2.16 on 2024-11-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Age', models.IntegerField()),
                ('Mail', models.EmailField(max_length=250, unique=True)),
                ('Mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('Image', models.ImageField(null=True, upload_to='users/')),
            ],
        ),
    ]
