# Generated by Django 4.2.16 on 2024-11-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryadminapp', '0002_remove_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Image',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
    ]
