# Generated by Django 4.2.16 on 2024-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryadminapp', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
    ]
